[WIP] Use SCM version to indicate development versions SCM to indicate development versions
cupy/cupy pull request #3478
Opened 2020-06-24 04:55 UTC by kmaehashi

When version is v8.0.0b3:

```
$ python setup.py --version
8.0.0b4.dev393+g6ddaac33e
```

2020-06-24 13:37 UTC, leofang commented
Just curious, do you know what's the difference between SCM and [versioneer](https://github.com/warner/python-versioneer)'s  approaches?

2020-06-25 16:43 UTC, leofang commented
I found some projects are moving away from versioneer to SCM: https://github.com/pytroll/satpy/issues/678

2020-06-26 06:29 UTC, kmaehashi commented
Actually I haven't ever used both 😅
AFAIK versioneer is feature-richer than setuptools_scm but needs to be included in the repository and seems not maintained well recently.  setuptools_scm is pypa's project (ie it's semi-official) and seems enough for us.

2020-06-26 15:54 UTC, leofang commented
Yeah the major concern for versioneer is it's no longer actively maintained... On the other hand, a valid argument is if it's included in the repo and it's working fine, it should not be maintained by upstream 😂 Anyway SCM is new and I'm happy there's a semi-official solution that could replace versioneer.

2020-08-24 04:58 UTC, kmaehashi commented
TODO: think about release sdist/wheel which is built before tagging at repo. Maybe add `--cupy-version x.y.z` option to override SCM version?

2020-08-24 05:01 UTC, leofang commented
I am curious, does SCM respect `cupy/_version.py`?

2020-11-05 08:39 UTC, emcastillo approved these changes

2020-11-05 08:40 UTC, emcastillo commented
Let's fix the conflict :(

2020-11-05 08:42 UTC, emcastillo commented
Jenkins, test this please

2020-11-05 09:11 UTC, emcastillo commented
```
raise RuntimeError('version information is not fouond: %s' % setup_path)
```

2021-01-26 05:36 UTC, emcastillo commented
seems like rtd is broken :(
```
ImportError: 
Error importing CuPy: version information could not be found.

It is likely that you are trying to import cupy from its source directory without building it;
please exit the cupy source tree, and relaunch your python interpreter from there.
```

2021-02-22 01:42 UTC, emcastillo commented
It seems to be working after adding the missing `setuptools_scm` package to the requirements for regular pip install and read the docs.

- I am not sure if `setuptools_scm` should be an install dependence, as sdist and the wheels will use the already bundled `VERSION` file. However it is needed for development and CIs.

Should we just do like we did with Cython, not add it as a dependence for other than CIs and modify the error message to let developers know that they need to install it.?

2021-02-22 04:47 UTC, kmaehashi commented
pfnCI, test this please.

2021-02-22 04:48 UTC, kmaehashi commented
pfnCI, test this please.

2021-02-22 05:30 UTC, kmaehashi commented
Blocked by : https://github.com/chainer/chainer-test/pull/636

2021-02-24 02:12 UTC, emcastillo commented
Jenkins, test this please

2021-02-24 02:12 UTC, emcastillo approved these changes

2021-03-04 07:07 UTC, leofang requested changes

2021-03-04 07:07 UTC, leofang commented on VERSION
> +v9.0.0b2
This should be bumped.

2021-03-15 17:30 UTC, leofang commented
Looks like Conda-Forge already supports SCM: https://github.com/conda-forge/conda-forge.github.io/pull/1274

2025-05-31 08:42 UTC, closed without merging