Use cuTENSOR in `cupy.prod`, `cupy.max`, `cupy.min`, `cupy.ptp` and `cupy.mean`
cupy/cupy pull request #3765
Opened 2020-08-11 20:10 UTC by asi1024

Blocked by #3700 and #3732.

2020-08-12 01:48 UTC, leofang commented
Nice! I was wondering when this PR would show up! 😁 Have you done any benchmarks?

2020-09-25 02:32 UTC, kmaehashi commented
pfnCI, test this please.

2020-09-26 20:36 UTC, leofang commented
Jenkins, test this please

2020-09-28 04:27 UTC, kmaehashi requested changes

2020-09-28 04:27 UTC, kmaehashi commented on cupy/core/_routines_statistics.pyx
> +if cupy.cuda.cutensor_enabled:
```suggestion
if cupy.cuda.cutensor.available:
```

2020-09-28 07:05 UTC, asi1024 commented
Jenkins, test this please.

2020-09-28 09:40 UTC, kmaehashi commented
@asi1024 Could you check test failures?

2020-09-29 09:10 UTC, asi1024 commented
Rebased.

2020-09-29 09:24 UTC, kmaehashi commented
pfnCI, test this please.

2020-09-29 09:25 UTC, asi1024 commented
pfnCI, test this please.

2020-09-29 11:24 UTC, kmaehashi commented
pfnCI, test this please.

2020-09-29 11:53 UTC, kmaehashi commented on cupy/core/_routines_statistics.pyx
> +from cupy import cutensor
This line needs to be removed.

2020-09-29 13:07 UTC, asi1024 commented
pfnCI, test this please.

2020-09-29 19:06 UTC, asi1024 commented
Jenkins, test this please.

2020-09-30 08:20 UTC, asi1024 commented
pfnCI, test this please.

2020-09-30 09:02 UTC, merged

2020-09-30 09:02 UTC, kmaehashi commented
LGTM!

2020-10-13 04:49 UTC, leofang commented
Looks like each backend has its own strength and there's no clear dominator. 
```python
import cupy as cp
import numpy as np
from cupyx.time import repeat


##cp.show_config()
#CUB_device_targets = ['sum', 'prod', 'min', 'max', 'argmax', 'argmin', 'cumsum', 'cumprod', 'mean']
#full_targets = CUB_device_targets + \
#                ['amin', 'amax', 'nanmin', 'nanmax', 'nanargmin', 'nanargmax',
#                 'nanmean',
#                 'var', 'nanvar', 'nansum', 'nanprod',
#                 'all', 'any', 'count_nonzero']
CUB_device_targets = ['sum', 'prod', 'min', 'max', 'ptp', 'mean']
full_targets = CUB_device_targets
dtypes = [cp.float32, cp.float64, cp.complex64, cp.complex128]
shape = (512, 512, 512)
axes = ((2,), (1, 2), (0, 1, 2))


for dtype in dtypes:
    a = cp.random.random(shape)
    if dtype in (cp.complex64, cp.complex128):
        a = a + 1j*cp.random.random(shape)
    a = a.astype(dtype)

    for target in full_targets:
        for axis in axes:
            if target in ('argmax', 'argmin', 'nanargmax', 'nanargmin', 'cumsum', 'cumprod'):
                if len(axis) != a.ndim:
                    continue
                else:
                    axis = None  # NumPy limitation
            if dtype in (cp.complex64, cp.complex128) and target in ('nanmin', 'nanmax', 'var', 'nanvar'):
                continue

            print(f"testing {target} with dtype={dtype} and axes={axis}...")
            func_cp = getattr(cp, target)
            func_np = getattr(np, target)

            cp.core.set_routine_accelerators([])
            cp.core.set_reduction_accelerators([])
            print(repeat(func_cp, (a, axis), n_repeat=20, name=f'no acce, {target}'))
            if not cp.allclose(func_cp(a, axis), func_np(cp.asnumpy(a), axis)):
                print(f"WARNING: CuPy's kernel might have a problem with {target} and {dtype}")

            if target in CUB_device_targets:
                cp.core.set_routine_accelerators(['cub'])
                cp.core.set_reduction_accelerators([])
                print(repeat(func_cp, (a, axis), n_repeat=20, name=f'CUB device, {target}'))
                if not cp.allclose(func_cp(a, axis), func_np(cp.asnumpy(a), axis)):
                    print(f"WARNING: CUB device might have a problem with {target} and {dtype}")

            cp.core.set_routine_accelerators([])
            cp.core.set_reduction_accelerators(['cub'])
            print(repeat(func_cp, (a, axis), n_repeat=20, name=f'CUB block, {target}'))
            if not cp.allclose(func_cp(a, axis), func_np(cp.asnumpy(a), axis)):
                print(f"WARNING: CUB block might have a problem with {target} and {dtype}")

            cp.core.set_routine_accelerators(['cutensor'])
            cp.core.set_reduction_accelerators([])
            print(repeat(func_cp, (a, axis), n_repeat=20, name=f'cuTENSOR, {target}'))
            if not cp.allclose(func_cp(a, axis), func_np(cp.asnumpy(a), axis)):
                print(f"WARNING: cuTENSOR might have a problem with {target} and {dtype}")
```
Output (nn the master branch + GTX 2080 Ti + CUDA 10.2):
```
testing sum with dtype=<class 'numpy.float32'> and axes=(2,)...
no acce, sum        :    CPU:   18.486 us   +/- 0.980 (min:   17.320 / max:   21.642) us     GPU-0: 4645.730 us   +/- 1.166 (min: 4644.704 / max: 4649.376) us
CUB device, sum     :    CPU:   38.436 us   +/- 1.244 (min:   37.203 / max:   41.870) us     GPU-0: 1244.704 us   +/- 3.474 (min: 1238.944 / max: 1253.632) us
CUB block, sum      :    CPU:   19.327 us   +/- 3.693 (min:   17.531 / max:   34.801) us     GPU-0:  942.299 us   +/- 3.943 (min:  940.192 / max:  957.344) us
cuTENSOR, sum       :    CPU:   16.881 us   +/- 0.805 (min:   16.149 / max:   19.402) us     GPU-0:  966.646 us   +/- 2.450 (min:  963.456 / max:  974.304) us
testing sum with dtype=<class 'numpy.float32'> and axes=(1, 2)...
no acce, sum        :    CPU:   17.294 us   +/- 0.608 (min:   16.466 / max:   18.534) us     GPU-0: 1160.214 us   +/- 2.895 (min: 1155.712 / max: 1167.232) us
CUB device, sum     :    CPU:   38.569 us   +/- 1.424 (min:   37.089 / max:   42.703) us     GPU-0:  953.930 us   +/- 2.134 (min:  951.168 / max:  959.520) us
CUB block, sum      :    CPU:   18.786 us   +/- 0.702 (min:   17.998 / max:   20.100) us     GPU-0:  942.715 us   +/- 1.984 (min:  939.712 / max:  946.784) us
cuTENSOR, sum       :    CPU:   16.659 us   +/- 0.967 (min:   15.681 / max:   20.322) us     GPU-0:  936.883 us   +/- 1.285 (min:  934.752 / max:  941.184) us
testing sum with dtype=<class 'numpy.float32'> and axes=(0, 1, 2)...
no acce, sum        :    CPU:   17.387 us   +/- 2.384 (min:   15.536 / max:   23.120) us     GPU-0:71086.148 us   +/- 8.248 (min:71072.540 / max:71101.151) us
CUB device, sum     :    CPU:   16.516 us   +/- 0.664 (min:   15.809 / max:   18.269) us     GPU-0:  931.430 us   +/- 0.879 (min:  930.432 / max:  934.080) us
CUB block, sum      :    CPU:   25.994 us   +/- 0.674 (min:   25.216 / max:   27.665) us     GPU-0:  962.715 us   +/- 0.735 (min:  961.856 / max:  964.992) us
cuTENSOR, sum       :    CPU:   19.171 us   +/- 0.697 (min:   18.330 / max:   20.893) us     GPU-0:  941.621 us   +/- 0.777 (min:  940.000 / max:  943.424) us
testing prod with dtype=<class 'numpy.float32'> and axes=(2,)...
no acce, prod       :    CPU:   18.168 us   +/- 0.790 (min:   17.006 / max:   19.931) us     GPU-0: 3361.712 us   +/- 0.814 (min: 3360.672 / max: 3363.904) us
CUB device, prod    :    CPU:   38.434 us   +/- 1.278 (min:   37.052 / max:   41.426) us     GPU-0: 1261.144 us   +/- 4.120 (min: 1255.648 / max: 1271.200) us
CUB block, prod     :    CPU:   18.533 us   +/- 0.795 (min:   17.561 / max:   20.596) us     GPU-0:  941.205 us   +/- 0.870 (min:  940.320 / max:  944.256) us
cuTENSOR, prod      :    CPU:   16.813 us   +/- 0.565 (min:   16.147 / max:   18.371) us     GPU-0: 1622.778 us   +/- 7.873 (min: 1603.904 / max: 1634.176) us
testing prod with dtype=<class 'numpy.float32'> and axes=(1, 2)...
no acce, prod       :    CPU:   17.329 us   +/- 0.530 (min:   16.423 / max:   18.655) us     GPU-0: 1255.805 us   +/-10.922 (min: 1210.208 / max: 1265.856) us
CUB device, prod    :    CPU:   38.407 us   +/- 1.228 (min:   37.205 / max:   41.521) us     GPU-0:  962.029 us   +/- 3.603 (min:  954.208 / max:  968.448) us
CUB block, prod     :    CPU:   19.198 us   +/- 1.023 (min:   18.195 / max:   22.711) us     GPU-0:  960.253 us   +/- 2.159 (min:  956.512 / max:  964.960) us
cuTENSOR, prod      :    CPU:   16.529 us   +/- 0.592 (min:   15.777 / max:   17.630) us     GPU-0: 1576.250 us   +/- 4.629 (min: 1568.000 / max: 1585.088) us
testing prod with dtype=<class 'numpy.float32'> and axes=(0, 1, 2)...
no acce, prod       :    CPU:   16.885 us   +/- 1.648 (min:   15.602 / max:   23.008) us     GPU-0:71090.276 us   +/- 7.642 (min:71072.739 / max:71108.543) us
CUB device, prod    :    CPU:   16.650 us   +/- 0.657 (min:   16.051 / max:   18.501) us     GPU-0:  933.526 us   +/- 1.054 (min:  932.160 / max:  936.480) us
CUB block, prod     :    CPU:   26.144 us   +/- 1.047 (min:   25.245 / max:   30.015) us     GPU-0:  962.798 us   +/- 1.082 (min:  961.728 / max:  966.176) us
cuTENSOR, prod      :    CPU:   19.431 us   +/- 0.649 (min:   18.513 / max:   20.866) us     GPU-0: 1476.314 us   +/- 9.113 (min: 1463.488 / max: 1507.616) us
testing min with dtype=<class 'numpy.float32'> and axes=(2,)...
no acce, min        :    CPU:   18.311 us   +/- 0.719 (min:   17.662 / max:   20.484) us     GPU-0: 3969.581 us   +/- 0.869 (min: 3968.832 / max: 3972.800) us
CUB device, min     :    CPU:   38.902 us   +/- 1.384 (min:   37.493 / max:   43.572) us     GPU-0: 1719.595 us   +/- 1.521 (min: 1717.888 / max: 1724.832) us
CUB block, min      :    CPU:   19.220 us   +/- 1.749 (min:   18.078 / max:   26.188) us     GPU-0:  942.779 us   +/- 1.735 (min:  941.440 / max:  949.376) us
cuTENSOR, min       :    CPU:   17.401 us   +/- 0.650 (min:   16.669 / max:   18.703) us     GPU-0: 1626.837 us   +/- 6.690 (min: 1611.26 [...]