Show numpy and scipy versions in `show_config`
cupy/cupy pull request #3768
Opened 2020-08-12 03:23 UTC by emcastillo

Currently `cupy.show_config` only shows cuda related info.
In order to easily lookup for errors in CI and locally, printing numpy and scipy versions as well can be helpful.

2020-08-12 03:36 UTC, leofang commented
Jenkins, test this please

2020-08-12 03:37 UTC, leofang commented
This closes #3629.

2020-08-16 11:15 UTC, emcastillo commented
TBD, show os, cc of the device and all the relevant info we can gather

2020-10-06 05:27 UTC, emcastillo commented
rebased

```
OS                           : Linux-4.15.0-112-generic-x86_64-with-debian-buster-sid
CuPy Version                 : 8.0.0rc1
NumPy Version                : 1.18.5
SciPy Version                : 1.4.1
CUDA Root                    : /usr/local/cuda-10.2
CUDA Build Version           : 11000
CUDA Driver Version          : 11000
CUDA Runtime Version         : 11000
cuBLAS Version               : 11200
cuFFT Version                : 10201
cuRAND Version               : 10201
cuSOLVER Version             : (10, 6, 0)
cuSPARSE Version             : 11101
NVRTC Version                : (11, 0)
Thrust Version               : 100909
CUB Build Version            : 100909
cuDNN Build Version          : 7500
cuDNN Version                : 7500
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
Device 0 Name                : Tesla V100-PCIE-16GB
Device 0 Compute Capability  : 70
```

2020-10-06 05:32 UTC, kmaehashi approved these changes
LGTM!

2020-10-06 05:32 UTC, kmaehashi commented
pfnCI, test this please.

2020-10-06 05:41 UTC, toslunar requested changes

2020-10-06 05:41 UTC, toslunar commented on cupyx/_runtime.py
> +import numpy
```suggestion
import numpy

import cupy
```

2020-10-06 05:55 UTC, emcastillo commented
Jenkins, test this please

2020-10-06 08:13 UTC, merged

2020-10-06 08:13 UTC, kmaehashi commented
LGTM!