Deprecate `cupy.sparse` package
cupy/cupy pull request #3839
Opened 2020-08-24 07:49 UTC by takagi

Close #3773.

This PR raises a deprecation warning for `cupy.sparse` package as discussed in #3773.

2020-08-24 09:26 UTC, toslunar commented
Jenkins, test this please.

2020-08-24 09:35 UTC, toslunar requested changes
Could you fix these lines?
```
% git grep -n 'from cupy import sparse\|import cupy\.sparse'
cupy/__init__.py:63:from cupy import sparse  # NOQA
cupyx/linalg/sparse/solve.py:7:import cupy.sparse
tests/cupyx_tests/linalg_tests/sparse_tests/test_solve.py:15:import cupy.sparse as sp
tests/cupyx_tests/scipy_tests/sparse_tests/test_index.py:5:from cupy import sparse
```

For tests, `warnings.catch_warnings` would be fine.

2020-08-24 15:02 UTC, takagi commented
I've fixed it to use module level `__getattr__` as well as changing the grepped lines to use `cupyx.scipy.sparse`. Would you check it again?

2020-08-24 15:13 UTC, kmaehashi commented
* Could you add a comment to `from cupy import sparse` in `cupy/__init__.py`?
* Could you fix `sparse.spmatrix` in `cupy/__init__.py` to use `cupyx.scipy.sparse`?

2020-08-24 15:35 UTC, kmaehashi commented
> @kmaehashi 96e0e44 follows what you intend?

Yes! (sorry for ambiguous comment :bow:)

2020-08-24 15:36 UTC, kmaehashi commented
Sorry I merged `_sorting` rename PR and now it starts to conflict...
pfnCI, test this please.

2020-08-24 16:30 UTC, kmaehashi commented
pfnCI, test this please.

2020-08-24 17:53 UTC, kmaehashi commented
pydoc:
```
cupyx/scipy/sparse/construct.py:        >>> from cupy.sparse import csr_matrix, hstack
cupyx/scipy/sparse/construct.py:        >>> from cupy.sparse import csr_matrix, vstack
cupyx/scipy/sparse/construct.py:        >>> from cupy.sparse import csr_matrix, bmat
```

examples:
```
examples/stream/cusparse.py:x = _make(cupy, cupy.sparse, float)
```

tests:
```
tests/cupy_tests/test_numpy_interop.py:        csr1 = cupy.sparse.csr_matrix((5, 3), dtype=numpy.float32)
```

2020-08-25 01:11 UTC, takagi commented
pfnCI, test this please.

2020-08-25 02:48 UTC, toslunar commented
pfnCI, test this please.

2020-08-25 02:50 UTC, toslunar approved these changes

2020-08-25 04:33 UTC, merged