add several functions to cupyx.scipy.ndimage.measurements
cupy/cupy pull request #3979
Opened 2020-09-10 21:47 UTC by grlee77

### Overview
This PR adds a series of related `cupyx.scipy.ndimage.measurement` functions: `maximum`, `maximum_position`, `minimum`, `minimum_position`, `median` and `extrema`.

### Implementation Notes

All of these rely on a single `_select` helper function that is patterned after SciPy's, but deviates in some implementation details.  Specifically, SciPy's implementation relies on NumPy-specific behavior regarding indexing with duplicate indices that is a [documented difference from CuPy behavior](https://docs.cupy.dev/en/stable/reference/difference.html#duplicate-values-in-indices)

[Example SciPy code](https://github.com/scipy/scipy/blob/48a876262d95fafbc44e7cbc7baa1ffd685ad659/scipy/ndimage/measurements.py#L867):

```Python
mins[labels[::-1]] = input[::-1]
```
For NumPy arrays, assuming `input` has already been sorted in ascending order, the line above results in storage of the minimum value at each integer values in `labels` to the corresponding index in `mins`. For CuPy, I instead relied on `lexsort` to get around the need for such repeated assignment to find the minimum or maximum (in contrast, SciPy only relies on `lexsort` for the `median` case, but only uses a simpler `argsort` of the labels for the other cases).

I later added an alternative code path (the `_select_via_looping` helper) that does not require `lexsort` and is much faster when there are relatively few labels to measure. It becomes slower than the `lexsort` approach when there are many (>30 or so) labels to measure. I think the slowdown for a larger number of labels is due to increasing numbers of kernel launches (but with relatively small work per kernel).

### One difference in behavior vs. SciPy

If there are multiple identical minima or maxima within a labeled region, the functions `minimum_position` and `maximum_position` as proposed here are not guaranteed to return the coordinates of the same extrema as the SciPy implementation. I think any of these duplicate extrema are equally valid choices, so I don't see this as a bug, but it is a deviation in behavior.

I couldn't see a very simple way to ensure we always get the same coordinate as SciPy. For that reason, `unittest.SkipTest` is used to skip cases where the input has non-unique values.

The other difference is that any global values returned by `minimum`, `maximum` and `median` are left as 0-dimensional device arrays rather than transferring to host scalars. I did choose to store the `minimum_position` and `maximum_position` values as tuples of int on the host, though I am not certain if that is preferred?

# Benchmarks 

Here are some benchmarks when CUB is enabled, showing that there is always substantial acceleration for large images, with the acceleration becoming particularly large (>100) when there are relatively few labels. Without CUB, there is reduced performance, but still an overall substantial acceleration. Results for `maximum` and `maximum_position` are not shown in the table because they should be the same as their `minimum` counterparts.

<details><summary>Benchmarks with CUB enabled</summary>

## Benchmarking functions from cupyx.scipy.ndimage.measurements

shape | GPU time (ms) | CPU time (ms) | acceleration
------|---------------|---------------|-------------
minimum, (128, 128), 1 label(s), uint8 | 0.018 +/- 0.002 | 0.017 +/- 0.002 | 0.978
minimum, (128, 128), 3 label(s), uint8 | 0.475 +/- 0.019 | 0.312 +/- 0.011 | 0.656
minimum, (128, 128), 10 label(s), uint8 | 0.966 +/- 0.035 | 0.324 +/- 0.018 | 0.335
minimum, (128, 128), 20 label(s), uint8 | 1.627 +/- 0.057 | 0.317 +/- 0.016 | 0.195
minimum, (128, 128), 50 label(s), uint8 | 0.728 +/- 0.023 | 0.310 +/- 0.010 | 0.426
minimum, (128, 128), 250 label(s), uint8 | 0.731 +/- 0.023 | 0.329 +/- 0.020 | 0.451
minimum, (512, 512), 1 label(s), uint8 | 0.017 +/- 0.001 | 0.194 +/- 0.012 | 11.212
minimum, (512, 512), 3 label(s), uint8 | 0.513 +/- 0.020 | 5.230 +/- 0.144 | 10.188
minimum, (512, 512), 10 label(s), uint8 | 1.115 +/- 0.034 | 5.325 +/- 0.096 | 4.778
minimum, (512, 512), 20 label(s), uint8 | 1.898 +/- 0.035 | 4.956 +/- 0.109 | 2.612
minimum, (512, 512), 50 label(s), uint8 | 1.703 +/- 0.071 | 5.204 +/- 0.066 | 3.056
minimum, (512, 512), 250 label(s), uint8 | 1.653 +/- 0.019 | 5.287 +/- 0.043 | 3.198
minimum, (4096, 4096), 1 label(s), uint8 | 0.059 +/- 0.000 | 11.834 +/- 0.166 | 199.192
minimum, (4096, 4096), 3 label(s), uint8 | 6.818 +/- 0.009 | 505.614 +/- 1.543 | 74.157
minimum, (4096, 4096), 10 label(s), uint8 | 20.095 +/- 0.016 | 503.091 +/- 1.499 | 25.036
minimum, (4096, 4096), 20 label(s), uint8 | 38.654 +/- 0.086 | 508.068 +/- 3.233 | 13.144
minimum, (4096, 4096), 50 label(s), uint8 | 100.349 +/- 0.080 | 492.171 +/- 1.988 | 4.905
minimum, (4096, 4096), 250 label(s), uint8 | 137.852 +/- 0.104 | 506.915 +/- 3.613 | 3.677
minimum_position, (128, 128), 1 label(s), uint8 | 0.160 +/- 0.009 | 0.086 +/- 0.007 | 0.538
minimum_position, (128, 128), 3 label(s), uint8 | 0.822 +/- 0.035 | 0.377 +/- 0.021 | 0.459
minimum_position, (128, 128), 10 label(s), uint8 | 1.844 +/- 0.062 | 0.366 +/- 0.018 | 0.199
minimum_position, (128, 128), 20 label(s), uint8 | 0.825 +/- 0.028 | 0.402 +/- 0.019 | 0.487
minimum_position, (128, 128), 50 label(s), uint8 | 0.849 +/- 0.028 | 0.400 +/- 0.016 | 0.471
minimum_position, (128, 128), 250 label(s), uint8 | 1.017 +/- 0.035 | 0.616 +/- 0.037 | 0.606
minimum_position, (512, 512), 1 label(s), uint8 | 0.171 +/- 0.006 | 1.069 +/- 0.011 | 6.265
minimum_position, (512, 512), 3 label(s), uint8 | 0.873 +/- 0.031 | 5.949 +/- 0.071 | 6.816
minimum_position, (512, 512), 10 label(s), uint8 | 2.046 +/- 0.055 | 5.764 +/- 0.144 | 2.818
minimum_position, (512, 512), 20 label(s), uint8 | 1.691 +/- 0.026 | 5.992 +/- 0.147 | 3.543
minimum_position, (512, 512), 50 label(s), uint8 | 1.749 +/- 0.027 | 5.941 +/- 0.119 | 3.396
minimum_position, (512, 512), 250 label(s), uint8 | 1.986 +/- 0.032 | 6.278 +/- 0.135 | 3.161
minimum_position, (4096, 4096), 1 label(s), uint8 | 2.843 +/- 0.006 | 80.222 +/- 0.158 | 28.216
minimum_position, (4096, 4096), 3 label(s), uint8 | 12.901 +/- 0.017 | 578.653 +/- 6.262 | 44.852
minimum_position, (4096, 4096), 10 label(s), uint8 | 36.639 +/- 0.044 | 583.947 +/- 1.371 | 15.938
minimum_position, (4096, 4096), 20 label(s), uint8 | 91.556 +/- 0.085 | 583.709 +/- 3.047 | 6.375
minimum_position, (4096, 4096), 50 label(s), uint8 | 105.014 +/- 0.075 | 581.576 +/- 1.129 | 5.538
minimum_position, (4096, 4096), 250 label(s), uint8 | 145.823 +/- 0.125 | 591.455 +/- 2.131 | 4.056
median, (128, 128), 1 label(s), uint8 | 0.074 +/- 0.004 | 0.068 +/- 0.004 | 0.927
median, (128, 128), 3 label(s), uint8 | 0.655 +/- 0.028 | 0.596 +/- 0.029 | 0.910
median, (128, 128), 10 label(s), uint8 | 1.515 +/- 0.053 | 0.723 +/- 0.033 | 0.477
median, (128, 128), 20 label(s), uint8 | 0.963 +/- 0.027 | 0.767 +/- 0.035 | 0.796
median, (128, 128), 50 label(s), uint8 | 0.997 +/- 0.035 | 0.848 +/- 0.031 | 0.851
median, (128, 128), 250 label(s), uint8 | 0.991 +/- 0.035 | 1.020 +/- 0.049 | 1.029
median, (512, 512), 1 label(s), uint8 | 0.078 +/- 0.005 | 0.877 +/- 0.032 | 11.238
median, (512, 512), 3 label(s), uint8 | 0.702 +/- 0.027 | 10.523 +/- 0.108 | 14.999
median, (512, 512), 10 label(s), uint8 | 1.669 +/- 0.042 | 13.817 +/- 0.219 | 8.276
median, (512, 512), 20 label(s), uint8 | 1.949 +/- 0.025 | 15.055 +/- 0.258 | 7.725
median, (512, 512), 50 label(s), uint8 | 1.910 +/- 0.025 | 16.291 +/- 0.334 | 8.528
median, (512, 512), 250 label(s), uint8 | 1.991 +/- 0.034 | 18.728 +/- 0.211 | 9.406
median, (4096, 4096), 1 label(s), uint8 | 0.799 +/- 0.002 | 49.111 +/- 0.503 | 61.431
median, (4096, 4096), 3 label(s), uint8 | 8.047 +/- 0.189 | 1090.444 +/- 3.095 | 135.516
median, (4096, 4096), 10 label(s), uint8 | 21.152 +/- 0.012 | 1720.172 +/- 2.107 | 81.324
median, (4096, 4096), 20 label(s), uint8 | 89.071 +/- 0.060 | 2001.175 +/- 3.524 | 22.467
median, (4096, 4096), 50 label(s), uint8 | 101.176 +/- 0.093 | 2250.323 +/- 0.313 | 22.242
median, (4096, 4096), 250 label [...]

2020-09-15 04:29 UTC, takagi commented
pfnCI, testthis please.

2020-09-23 06:13 UTC, takagi commented
pfnCI, test this please.

2020-09-24 06:13 UTC, takagi requested changes
Would you check a comment on the test?

2020-09-24 06:24 UTC, takagi commented
It is fine that `minimum`, `maximum` and `median` return 0-dimensional device arrays rather than host scalars. As for the returned tuples of `minimum_position` and `miximum_position`, let me ask it for other core members.

2020-09-24 06:30 UTC, takagi commented
Would you add the reference entries on `docs/source/reference/ndimage.rst`?

2020-10-13 07:24 UTC, takagi commented
@grlee77 Kindly ping.

2020-10-13 11:49 UTC, grlee77 commented
> @grlee77 Kindly ping.

I rebased to fix the merge conflict. The last two commits were added to update the API docs and avoid unintentionally skipping dtype tests. I apparently did this awhile back, but forgot to ever push the changes to the remote branch!

2020-10-15 10:29 UTC, takagi requested changes
Would you make minor fixes on docstrings?

2020-10-15 10:41 UTC, takagi requested changes
Would you check another comment on `extrema`'s docstring?

2020-10-15 10:41 UTC, takagi commented on cupyx/scipy/ndimage/measurements.py
> +            coordinates of the corresponding maximum.
It seems that Sphinx (or its extension) strictly allows only a return value with the following grammar:

    Returns:
        <Return type>: <Description>

As the return type is optional and the description can be multiple lines, would you arrange the part as something like below? (I tried to escape the colon, but sphinx did not read the part as so)


```suggestion
    Returns:
        A tuple that contains the following values.

        minimums (cupy.ndarray): Values of minimums in each feature.

        maximums (cupy.ndarray): Values of maximums in each feature.

        min_positions (tuple or list of tuples):
            Each tuple gives the N-D coordinates of the corresponding minimum.

        max_positions (tuple or list of tuples):
            Each tuple gives the N-D coordinates of the corresponding maximum.
```

2020-10-15 14:14 UTC, grlee77 commented
Thanks @takagi. After committing the suggestions, the extrema docstring rendered as follows:
![000](https://user-images.githubusercontent.com/6528957/96141508-16e41e80-0ecf-11eb-9ca9-8c28987d30cc.png)


I tweaked it a bit in 1d11969, resulting in:
![001](https://user-images.githubusercontent.com/6528957/96141519-19467880-0ecf-11eb-8cd0-1b47e8f6c28c.png)

2020-10-15 15:04 UTC, takagi commented
Thanks, it's fine!

2020-10-15 15:05 UTC, takagi commented
pfnCI, test this please.

2020-10-15 15:24 UTC, takagi approved these changes

2020-10-16 03:04 UTC, takagi requested changes
I totally checked the docstrings, and would you make additional fixes? Others look good to me.

2020-10-16 03:04 UTC, takagi commented on cupyx/scipy/ndimage/measurements.py
> +            `input`.
Looks corrupted render.
```suggestion
        list of tuples of ints: Tuple of ints or list of tuples of
        ints that specify the location of maxima of `input` over the
        regions determaxed by `labels` and  whose index is in `index`.

        If `index` or `labels` are not specified, a tuple of ints is
        returned specifying the location of the first maximal value of
        `input`.
```

2020-10-16 15:22 UTC, grlee77 commented on cupyx/scipy/ndimage/measurements.py
> +            zero if `index` is None.
Thanks for catching these. On closer look, this does seem to be what the Google docstring format requires.

2020-10-18 06:42 UTC, takagi approved these changes

2020-10-18 06:43 UTC, takagi commented
pfnCI, test this please.

2020-10-19 03:44 UTC, takagi commented
LGTM!

2020-10-19 03:44 UTC, merged