Move `_normalize_axis_index` to `cupy/core/internal.pyx`
cupy/cupy pull request #4057
Opened 2020-10-02 18:26 UTC by asi1024

2020-10-02 20:33 UTC, grlee77 approved these changes
Looks good. Thanks @asi1024

2020-10-02 21:00 UTC, leofang commented
Perhaps we could cythonize the two moved functions, making them cpdef'd?

2020-10-05 05:52 UTC, asi1024 commented
Made them cpdef.

2020-10-06 02:22 UTC, takagi commented
LGTM! Would you resolve the conflict? Then, I'll kick the CI.

2020-10-06 17:21 UTC, asi1024 commented
Resolved the conflict.

2020-10-06 19:04 UTC, leofang requested changes

2020-10-06 19:04 UTC, leofang commented on cupy/core/_fusion_trace.pyx
> +from cupy.core import internal
```suggestion
from cupy.core cimport internal
```

2020-10-06 19:04 UTC, leofang commented on cupy/core/_routines_math.pyx
> +from cupy.core import internal
```suggestion
from cupy.core cimport internal
```

2020-10-06 20:24 UTC, leofang commented
Jenkins, test this please

2020-10-06 20:24 UTC, leofang approved these changes
LGTM!

2020-10-07 03:44 UTC, merged