Parameterize sparse matrix tests
cupy/cupy pull request #4368
Opened 2020-11-30 13:23 UTC by takagi

This PR parameterizes some tests for sparse matrix formats.

2020-11-30 13:23 UTC, takagi commented
pfnCI, test this please.

2020-11-30 23:53 UTC, takagi commented
Looks that we can not naively use parameterized dtype tests and `pytest.mark.parametrize` at the same time.

2020-12-01 04:54 UTC, takagi commented
pfnCI, test this please.

2020-12-01 07:17 UTC, takagi commented
Should we provide an API in `cupy.testing` as opposed to use `pytest.mark.parametrize`?

2020-12-02 02:27 UTC, toslunar requested changes

2020-12-02 02:27 UTC, toslunar commented on tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
> +        a = sp.coo_matrix(a).as_format(format)
```suggestion
        a = sp.coo_matrix(a).asformat(format)
```

2020-12-02 14:12 UTC, takagi commented on tests/cupyx_tests/scipy_tests/sparse_tests/test_linalg.py
> +        a = sp.coo_matrix(a).as_format(format)
oh...

2020-12-03 01:50 UTC, toslunar approved these changes

2020-12-03 01:50 UTC, toslunar commented
pfnCI, test this please.

2020-12-03 04:18 UTC, takagi commented
`TestCG` is not skipped?

2020-12-03 04:19 UTC, toslunar requested changes
`unittest.skipUnless` (and `unittest.skipIf`) cannot decorate a non-`unittest.TestCase` **class** .  Use `cupy.testing.with_requires` instead.

2020-12-03 09:32 UTC, toslunar commented
pfnCI, test this please.

2020-12-03 11:14 UTC, toslunar approved these changes

2020-12-04 05:43 UTC, merged