Remove experimental warnings from cupyx.scipy.ndimage
cupy/cupy pull request #4518
Opened 2021-01-04 14:30 UTC by grlee77

These should no longer be needed now that SciPy 1.6.0 [has been released](https://github.com/scipy/scipy/releases/tag/v1.6.0)

2021-01-05 04:47 UTC, toslunar requested changes
Could you remove the imports, too?
```python
import cupy._util
```

2021-01-05 10:45 UTC, grlee77 commented
The unused import has now been removed.

2021-01-06 01:57 UTC, toslunar commented
Is `cupy._util` used in `cupyx/scipy/ndimage/interpolation.py`?  The occurrences of `_util` there are `cupyx.scipy.ndimage._util`.

2021-01-16 19:08 UTC, grlee77 commented
> Is cupy._util used in cupyx/scipy/ndimage/interpolation.py? The occurrences of _util there are cupyx.scipy.ndimage._util.

whoops, missed that one. It has now been removed

2021-01-17 08:27 UTC, takagi commented
Close #4467

2021-01-18 04:37 UTC, toslunar approved these changes

2021-01-18 04:38 UTC, toslunar commented
pfnCI, test this please.

2021-01-18 05:50 UTC, merged