[backport] Fix tests for incompatible behavior of NumPy 1.20 linspace
cupy/cupy pull request #4625
Opened 2021-02-04 15:46 UTC by asi1024

Backport of https://github.com/cupy/cupy/pull/4604

2021-02-05 06:53 UTC, toslunar requested changes
```
>>> req, = pkg_resources.parse_requirements('numpy>=1.16<1.20'); req.specs
[('>=', '1.16<1.20')]
>>> req, = pkg_resources.parse_requirements('numpy>=1.16,<1.20'); req.specs
[('<', '1.20'), ('>=', '1.16')]
```

2021-02-05 06:53 UTC, toslunar commented on tests/cupy_tests/creation_tests/test_ranges.py
> +    @testing.with_requires('numpy>=1.16<1.20')
```suggestion
    @testing.with_requires('numpy>=1.16,<1.20')
```

2021-02-05 06:53 UTC, toslunar commented on tests/cupy_tests/creation_tests/test_ranges.py
> +    @testing.with_requires('numpy>=1.16<1.20')
```suggestion
    @testing.with_requires('numpy>=1.16,<1.20')
```

2021-02-05 13:58 UTC, asi1024 commented
Jenkins, test this please.

2021-02-06 04:05 UTC, toslunar approved these changes

2021-02-06 04:06 UTC, merged