[backport] Update doctest of `cupyx.scipy.linalg.lu_factor`
cupy/cupy pull request #4627
Opened 2021-02-05 06:05 UTC by kmaehashi

Backport of #4561

2021-02-05 06:05 UTC, kmaehashi commented
[automatic post] Jenkins, test this please.

2021-02-09 06:28 UTC, takagi commented
pfnCI, test this please.

2021-02-09 06:29 UTC, takagi commented
LGTM! Waiting for CI pass.

2021-02-20 05:05 UTC, takagi requested changes
LGTM except for one!

2021-02-20 05:05 UTC, takagi commented on tests/cupyx_tests/scipy_tests/linalg_tests/test_decomp_lu.py
> +    @testing.for_dtypes('fdFD')
Would you remove this decorator from the helper method?

2021-03-23 14:34 UTC, closed without merging