[WIP] Support batched `pinv`
cupy/cupy pull request #4686
Opened 2021-02-19 06:29 UTC by leofang

***Blocked by #4684*** as batched SVD is required.

Close #3062.

The original implementation already followed NumPy's, so really it's just adding `newaxis` here and there to broadcast.

2021-02-22 08:15 UTC, leofang commented
Jenkins, test this please

2021-02-24 11:12 UTC, toslunar requested changes

2021-02-25 06:57 UTC, leofang commented on tests/cupy_tests/linalg_tests/test_solve.py
> +        self.check_x((0, 0), rcond=1e-15)
Thanks, added it!

2021-02-25 06:57 UTC, leofang commented on tests/cupy_tests/linalg_tests/test_solve.py
> +                            [0.2, 0.2, 0.2]])
Updated in da610ee.

2021-02-25 06:58 UTC, leofang commented
Thanks, @toslunar! Your suggestions make it much cleaner 👍

2021-02-26 14:53 UTC, leofang commented
Jenkins, test this please

2021-03-01 09:42 UTC, toslunar approved these changes

2021-03-02 06:05 UTC, merged

2021-03-02 06:18 UTC, leofang commented
Thanks, @toslunar!