Add Docker image for ROCm
cupy/cupy pull request #4737
Opened 2021-02-24 15:42 UTC by kmaehashi

2021-02-25 15:25 UTC, leofang requested changes

2021-02-25 15:25 UTC, leofang commented on docs/source/install_rocm.rst
> +  You can specify comma-separated list of ISAs if you have multiple GPUs of different architecture.
```suggestion
  You can specify a comma-separated list of ISAs if you have multiple GPUs of different architectures.
```

2021-02-25 15:25 UTC, leofang commented on docs/source/install_rocm.rst
> +* ``HCC_AMDGPU_TARGET``: ISA name supported by your GPU.
According to the ongoing discussion https://github.com/cupy/cupy/issues/4719#issuecomment-785981214 it seems we don't have to set `HCC_AMDGPU_TARGET` at runtime.

2021-02-25 15:25 UTC, leofang commented on docs/source/install_rocm.rst
> -You may also need to set ``ROCM_HOME`` (e.g., ``ROCM_HOME=/opt/rocm``).
I think we still need to set `ROCM_HOME` for the time being:
https://github.com/cupy/cupy/blob/f4751f1d4d145410e2268609c011fbf894775bc7/install/build.py#L45

2021-02-26 04:01 UTC, leofang submitted a review, later dismissed
LGTM except for one nitpick in language. I forgot that we still check `HCC_AMDGPU_TARGET` in `compiler.py` 😅 I can send a PR to remove it after the code freeze.

2021-02-26 04:16 UTC, kmaehashi commented
Thanks @leofang!

2021-02-26 07:22 UTC, asi1024 commented
LGTM!

2021-02-26 07:22 UTC, merged