Deprecate `cupy.bool`, `cupy.int`, `cupy.float` and `cupy.complex`
cupy/cupy pull request #4790
Opened 2021-03-02 11:32 UTC by asi1024

Resolve #4755

2021-03-03 09:19 UTC, toslunar requested changes

2021-03-03 09:19 UTC, toslunar commented on cupy/__init__.py
> +                f"module 'cupy' has no attribute '{name}'")
For `getattr(cupy, '\n')`, `getattr(cupy, "'")`, and etc,
```suggestion
                f"module 'cupy' has no attribute {name!r}")
```

I found this repr (`!r`) in [PEP 562](https://www.python.org/dev/peps/pep-0562/), [in NumPy](https://github.com/numpy/numpy/blob/168978df69efecb07943fd8ce3a7c95aab7122cb/numpy/__init__.py#L308-L309), and [in unittest](https://github.com/python/cpython/blob/94894dd45e4bad6efb27eac4497b24cdc18b3e2d/Lib/unittest/__init__.py#L95), even though the default behavior is similar to `f"'{name}'"`.

```
>>> getattr(sys, '\n')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'sys' has no attribute '
'
>>> getattr(numpy, '\n')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../numpy/__init__.py", line 303, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute '\n'
```

2021-03-04 04:56 UTC, toslunar submitted a review, later dismissed

2021-03-04 07:21 UTC, asi1024 commented
Rebased.

2021-03-04 07:21 UTC, toslunar approved these changes

2021-03-04 07:21 UTC, toslunar commented
pfnCI, test this please.

2021-03-04 09:56 UTC, merged