[backport] Fix dtypes in `cupy.linalg`
cupy/cupy pull request #4839
Opened 2021-03-09 01:12 UTC by emcastillo

Backport of #4363

2021-03-09 01:12 UTC, emcastillo commented
[automatic post] Jenkins, test this please.

2021-03-09 05:18 UTC, emcastillo commented
Jenkins, test this please

2021-03-10 02:30 UTC, toslunar requested changes
LGTM except for the line.

2021-03-10 02:30 UTC, toslunar commented on cupy/linalg/_solve.py
> +    print('types ', a.dtype, dtype, out_dtype)
```suggestion
```

2021-03-10 02:32 UTC, emcastillo commented
Jenkins, test this please

2021-03-10 05:33 UTC, toslunar approved these changes

2021-03-10 05:34 UTC, merged