Skip cuTENSOR/cuSPARSELt installation for unsupported CUDA version
cupy/cupy pull request #5050
Opened 2021-04-07 08:47 UTC by asi1024

2021-04-26 16:09 UTC, leofang commented
#5136 may be relevant.

2021-06-29 05:29 UTC, kmaehashi requested changes

2021-06-29 05:29 UTC, kmaehashi commented on cupy_setup_build.py
> +        elif ('required_cuda_version' in module
This needs to be checked first (before `not check_library()` condition) to skip building cuTENSOR/cuSPARSELt support for unsupported CUDA versions.

2021-06-29 05:29 UTC, kmaehashi commented on cupy_setup_build.py
> +                f'The library is not supported for CUDA {cuda_major_minor}']
```suggestion
                f'Not supported in CUDA {cuda_major_minor}']
```

2023-06-19 05:47 UTC, kmaehashi commented
I think this doesn't make much sense after dropping CUDA 10.2... maybe it's ok to close? @asi1024 :bow:

2023-06-20 08:46 UTC, closed without merging