Fix PTDS destruction
cupy/cupy pull request #5156
Opened 2021-04-28 04:15 UTC by emcastillo

Closes #5145 

The actual stream tests show this error, but due to [Python ignoring exceptions in `__del__`](http://docs.python.org/2/reference/datamodel.html#object.__del__) methods they never failed when they should have done it :).

> Warning: Due to the precarious circumstances under which __del__() methods are invoked, exceptions that occur during their execution are ignored, and a warning is printed to sys.stderr instead. Also, when __del__() is invoked in response to a module being deleted (e.g., when execution of the program is done), other globals referenced by the __del__() method may already have been deleted or in the process of being torn down (e.g. the import machinery shutting down). For this reason, __del__() methods should do the absolute minimum needed to maintain external invariants. Starting with version 1.5, Python guarantees that globals whose name begins with a single underscore are deleted from their module before other globals are deleted; if no other references to such globals exist, this may help in assuring that imported modules are still available at the time when the __del__() method is called.

2021-04-29 14:12 UTC, leofang commented on cupy/cuda/stream.pyx
> +        if self.ptr and self.ptr != runtime.streamPerThread:
Just a nitpick: Can we also include `streamLegacy` here to be future-proof? See
https://github.com/cupy/cupy/blob/8cf5983112a4e90fe5e83b8daec5e55da472f400/cupy/cuda/stream.pyx#L322-L325
```suggestion
        if self.ptr not in (0, 1, 2):
```

2021-05-04 00:02 UTC, jakirkham commented
cc @pentschev

2021-05-06 03:36 UTC, kmaehashi requested changes

2021-05-06 03:36 UTC, kmaehashi commented on cupy/cuda/stream.pyx
>                  tls.set_current_stream(self.null)
Stream must be reverted to PTDS when PTDS is enabled.

2021-05-18 02:27 UTC, kmaehashi commented
Closing as @leofang's PR #5172 includes the fix for this issue  😄

2021-05-18 02:27 UTC, closed without merging