Add NVCC path and Python version to `show_config`
cupy/cupy pull request #5215
Opened 2021-05-20 09:10 UTC by asi1024

Resolve #5210.

2021-05-20 13:00 UTC, kmaehashi requested changes

2021-05-20 13:00 UTC, kmaehashi commented on cupyx/_runtime.py
> +            ('Python Version', platform.python_version()),
Could you move this line to just after `OS`?

2021-05-20 13:00 UTC, kmaehashi commented on cupyx/_runtime.py
>              ('CuPy Version', self.cupy_version),
Let's add platform information too.

```suggestion
            ('CuPy Version', self.cupy_version),
            ('CuPy Platform', 'NVIDIA CUDA' if not is_hip else 'AMD ROCm'),
```

2021-05-20 13:00 UTC, kmaehashi commented on cupyx/_runtime.py
> +        compiler_name = 'hipcc' if is_hip else 'NVCC'
```suggestion
        compiler_name = 'hipcc' if is_hip else 'nvcc'
```

2021-05-20 13:00 UTC, kmaehashi commented on cupyx/_runtime.py
> +            (f'{compiler_name} PATH', self.nvcc_path)
Could you move this line just after `CUDA Root`?

2021-05-21 07:19 UTC, asi1024 commented
@kmaehashi PTAL!

2021-05-21 07:20 UTC, kmaehashi commented
pfnCI, test this please.

2021-05-21 07:20 UTC, kmaehashi approved these changes
LGTM!

2021-05-21 10:22 UTC, merged