Support detecting cl.exe in vs2019
cupy/cupy pull request #5292
Opened 2021-05-28 14:10 UTC by eternalphane

Use `setuptools.msvc` instead of `distutils.msvc9compiler` to detect cl.exe

2021-05-29 06:33 UTC, kmaehashi commented
Thanks @eternalphane!

It looks nice to discover VS2019, however I'm concerning that CUDA 10.0, which is still in our supported CUDA version, does not support VS2019.
https://docs.nvidia.com/cuda/archive/10.0/cuda-installation-guide-microsoft-windows/index.html
Let me try your patch on CUDA 10.0 environment later.

2021-05-30 02:37 UTC, leofang requested changes
Thanks for your patch. I do not have access to any Windows CUDA env, so I cannot verify the patch and I think @kmaehashi and others from the team will help. But, for the purpose of #4983 I think this PR is necessary for us to move away from depending `distutils` at runtime, so I am happy to see this change!

With the above background stated, @eternalphane could you try replacing all `distutils` occurrences in this file (likely only contained in the function you're touching) by their `setuptools` counterparts and help us verify the change please? I think PEP 632 should be clear in the needed replacements so it should be rather straightforward.

2021-06-17 13:39 UTC, kmaehashi requested changes

2021-06-17 13:39 UTC, kmaehashi commented on cupy/cuda/compiler.py
> +    import shutil
Could you move this import (and `import platform` too --- as they're standard modules) to the top of the file?

2021-06-17 13:39 UTC, kmaehashi commented on cupy/cuda/compiler.py
> +    from setuptools.errors import DistutilsError
It seems `setuptools.errors` is only available in setuptools v42.0+. In my environment, the default one that comes with Python 3.8 for Windows was 41.2.0, so this line failed. Until we decide a policy on which setuptools versions to support (we should do this once we fully migrate from distutils), I'm negative to use this module. So, could you use `distutils.errors.DistutilsPlatformError` instead, as in your original code? :pray:

2021-06-17 13:39 UTC, kmaehashi commented on cupy/cuda/compiler.py
> +    if not shutil.which('cl.exe', path):
```suggestion
    if not shutil.which('cl.exe', path=path):
```

2021-06-17 13:47 UTC, kmaehashi commented
Could you fix the comments here as well?

https://github.com/cupy/cupy/blob/b01641dedb065f65a4d3f846cf3c6222693a8e44/cupy/cuda/compiler.py#L54-L56

`the VC++ compiler used to build Python / CuPy to the PATH` -> `the latest VC++ compiler found via setuptools`

2021-11-18 12:58 UTC, kmaehashi commented
I've tookover the work in #6025.

2021-11-18 12:58 UTC, closed without merging