Fix unwrap return type
cupy/cupy pull request #5385
Opened 2021-06-23 02:56 UTC by emcastillo

For Numpy 1.21 compat

2021-06-28 10:18 UTC, kmaehashi commented
In NumPy 1.21 the dtype is derived from `p` and new option `period`, so seems it can be even an integer.
https://github.com/numpy/numpy/pull/16987/files#diff-077cb9d49365526e8128efeeca9d2cf1646bab14b7c3125d0282603d35ea0fbeR1558

2021-06-28 11:49 UTC, emcastillo commented
Thanks for the pointer! I should have checked the numpy documentation first ...
I synced the routine to that of numpy now, should be ok :).

I will add tests tomorrow

2021-06-29 08:15 UTC, emcastillo commented
Tests added, wonder if we should parameterize them or it is fine to leave them as they are.

2021-06-29 11:47 UTC, kmaehashi commented on cupy/_math/trigonometric.py
> +    if numpy.core.numeric.issubdtype(dtype, numpy.core.numeric.integer):
Let's use documented API :smile:
```suggestion
    if numpy.issubdtype(dtype, numpy.core.numeric.integer):
```

2021-06-29 11:49 UTC, kmaehashi requested changes
Could you fix the docs indentation?
https://cupy--5385.org.readthedocs.build/en/5385/reference/generated/cupy.unwrap.html

2021-06-29 12:38 UTC, emcastillo commented
should be ok now :)

2021-06-29 12:57 UTC, emcastillo commented
Docs preview:

https://cupy--5385.org.readthedocs.build/en/5385/reference/generated/cupy.unwrap.html#cupy.unwrap

2021-06-30 04:28 UTC, kmaehashi commented
LGTM!
pfnCI, test this please.

2021-06-30 08:51 UTC, kmaehashi approved these changes

2021-06-30 08:52 UTC, merged