Fix signaltools `medfilt` for `scipy>=1.7.0`
cupy/cupy pull request #5386
Opened 2021-06-23 02:59 UTC by emcastillo

2021-07-05 08:04 UTC, emcastillo commented
rtd failure seems unrelated

2021-07-08 05:14 UTC, toslunar requested changes

2021-07-08 05:14 UTC, toslunar commented on cupyx/scipy/signal/signaltools.py
> +        raise ValueError("only supports uint8, float32, and float64")
The old check seems correct.
```
>>> scipy.signal.medfilt(np.array([3, 1, 4, 1, 5, 9, 2, 6], np.int16))
array([1, 3, 1, 4, 5, 5, 6, 2], dtype=int16)
>>> scipy.__version__
'1.7.0'
```

2021-07-08 06:17 UTC, emcastillo commented on cupyx/scipy/signal/signaltools.py
> +        raise ValueError("only supports uint8, float32, and float64")
good catch! thanks :)

2021-07-08 06:37 UTC, toslunar reviewed
Could you revert the order of `for_all_dtypes` and `numpy_cupy_allclose`?
```diff
--- a/tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
+++ b/tests/cupyx_tests/scipy_tests/signal_tests/test_signaltools.py
@@ -255,9 +255,9 @@ class TestOrderFilter(unittest.TestCase):
 @testing.gpu
 @testing.with_requires('scipy>=1.7.0')
 class TestMedFilt(unittest.TestCase):
+    @testing.for_all_dtypes()
     @testing.numpy_cupy_allclose(atol=1e-8, rtol=1e-8, scipy_name='scp',
                                  accept_error=ValueError)  # for even kernels
-    @testing.for_all_dtypes()
     def test_medfilt(self, xp, scp, dtype):
         if sys.platform == 'win32':
             pytest.xfail('medfilt broken for Scipy 1.7.0 in windows')
@@ -275,9 +275,9 @@ class TestMedFilt(unittest.TestCase):
 @testing.gpu
 @testing.with_requires('scipy>=1.7.0')
 class TestMedFilt2d(unittest.TestCase):
+    @testing.for_all_dtypes()
     @testing.numpy_cupy_allclose(atol=1e-8, rtol=1e-8, scipy_name='scp',
                                  accept_error=ValueError)  # for even kernels
-    @testing.for_all_dtypes()
     def test_medfilt2d(self, xp, scp, dtype):
         if sys.platform == 'win32':
             pytest.xfail('medfilt2d broken for Scipy 1.7.0 in windows')
```

2021-07-12 00:50 UTC, emcastillo commented
done!

2021-07-13 02:35 UTC, toslunar commented
Jenkins, test this please.

2021-07-13 02:35 UTC, toslunar approved these changes

2021-07-13 09:01 UTC, toslunar commented
Jenkins, test this please.

2021-07-13 11:08 UTC, merged

2021-07-13 12:33 UTC, kmaehashi commented
Thanks @toslunar :pray:

2021-07-14 01:22 UTC, toslunar commented
I'll backport dad44ee7b7bbd410882ea0a9e6c48d5e6e6f6c99.

2021-07-19 02:45 UTC, toslunar commented
I suppose this PR should be backported.  The corrected tests (#5518) are failing in v9.