Add Power distribution to Generator
cupy/cupy pull request #5624
Opened 2021-08-09 18:14 UTC by povinsahu1909

This PR adds power distribution to Generator.

Following is the performance comparison on GTX1050.

size(nrows * ncols) | numpy (sec) | cupyx (sec)
--- | --- | ---
10000 * 1 | 0.000 | 0.000
12000 * 1 | 0.001 | 0.000
15000 * 1 | 0.001 | 0.000
20000 * 1 | 0.001 | 0.000
10000 * 1000 | 0.409 | 0.050
12000 * 1000 | 0.509 | 0.061
15000 * 1000 | 0.616 | 0.079
20000 * 1000 | 0.828 | 0.115
10000 * 2000 | 0.831 | 0.101
12000 * 2000 | 0.988 | 0.120
15000 * 2000 | 1.235 | 0.151
20000 * 2000 | 1.685 | 0.201
10000 * 3000 | 1.306 | 0.169
12000 * 3000 | 1.579 | 0.204
15000 * 3000 | 1.864 | 0.224
20000 * 3000 | 2.522 | 0.312

<details>
<summary>script</summary>

```python

import numpy as np
import cupy as cp
import cupyx

n_repeat = 2
n_warmup = 1
crng = cp.random.default_rng()
nrng = np.random.default_rng()

def get_time(perf):
    cpu_time = perf.cpu_times.mean()
    gpu_time = perf.gpu_times.mean()
    return max(cpu_time, gpu_time)

def run(p, q):
    times = []

    perf = cupyx.time.repeat(nrng.power, (p,),
                            n_repeat=n_repeat, n_warmup=n_warmup)
    times.append(get_time(perf))
    perf = cupyx.time.repeat(crng.power, (q,),
                            n_repeat=n_repeat, n_warmup=n_warmup)
    times.append(get_time(perf))
    return times

print('size(nrows * ncols) | numpy (sec) | cupyx (sec)')
print('---|---|---')
nrows = [10000, 12000, 15000, 20000]
ncols = [1, 1000, 2000, 3000]
for m in ncols:
    for n in nrows:
        p = np.random.random((n, m))
        q = cp.asarray(p)
        times = run(p, q)
        print('{} * {} | {:.3f} | {:.3f}'.format(n, m, times[0], times[1]))

2021-08-10 00:29 UTC, emcastillo commented on cupy/random/cupy_distributions.cu
> +struct power_functor {
There is already a `standard_exponential_functor` no need to alias it

2021-08-10 00:30 UTC, emcastillo commented on cupy/random/cupy_distributions.cu
> +struct power_functor {
Also you are not using this one 😄

2021-08-10 00:30 UTC, emcastillo commented on cupy/random/cupy_distributions.cu
> +
```suggestion
```

2021-08-10 00:30 UTC, emcastillo commented on cupy/random/cupy_distributions.cu
> +
```suggestion
```

2021-08-10 00:31 UTC, emcastillo commented on cupy/random/cupy_distributions.cuh
> +void power(int generator, intptr_t state, intptr_t out, ssize_t size, intptr_t stream);
```suggestion
```

2021-08-10 00:31 UTC, emcastillo commented on cupy/random/cupy_distributions.cuh
> +void power(int generator, intptr_t state, intptr_t out, ssize_t size, intptr_t stream) {}
```suggestion
```

2021-08-10 00:31 UTC, emcastillo commented on cupy/random/_generator_api.pyx
> +        ssize_t size, intptr_t stream)
```suggestion
```

2021-08-10 00:32 UTC, emcastillo requested changes
You added a `power` function but you are not using it (Which is cool)
please remove it :)

2021-08-11 00:43 UTC, emcastillo commented on tests/cupy_tests/random_tests/common_distributions.py
> +    {'a': [0.8, 0.7, 1, 2, 5]},
won't this parameter be ignored by the below checks?

2021-08-11 00:44 UTC, emcastillo commented
Jenkins, test this please

2021-08-11 03:11 UTC, takagi submitted a review, later dismissed

2021-08-11 03:11 UTC, takagi commented
Jenkins, test this please

2021-08-12 05:45 UTC, takagi approved these changes

2021-08-12 05:46 UTC, takagi commented
pfnCI, test this please.

2021-08-12 05:48 UTC, takagi commented
LGTM!

2021-08-13 05:07 UTC, takagi commented
@emcastillo would you approve the change?

2021-08-16 06:00 UTC, emcastillo approved these changes

2021-08-16 06:00 UTC, merged