Use `__all__` for comparison table generator
cupy/cupy pull request #6072
Opened 2021-11-11 15:23 UTC by kmaehashi

This hides several APIs that are unexpectedly exposed.

https://gist.github.com/kmaehashi/8e89e6cfd863a4bc0746b90c3467b795

2021-11-11 16:18 UTC, toslunar commented on docs/source/_comparison_generator.py
> +    children = obj.__all__ if hasattr(obj, '__all__') else dir(obj)
`__all__` can contain "private" names that start with `_`.  How about moving the condition `not n.startswith('_')` here? (For example, which I admit not really a good example, `'__version__' in numpy.__all__`).

I'm not sure if default `__all__` contains submodule names, but it looks always fine to exclude submodules from the comparison table.

```suggestion
    try:
        children = obj.__all__
    except AttributeError:
        children = [n for n in dir(obj) if not n.startswith('_')]
```

2021-11-12 09:51 UTC, toslunar requested changes
I'd like to preserve `abs`, `max`, `min`, and `round`.  NumPy excludes the names in builtins from `numpy.__all__`.  They are shorthand of `absolute`, `amax`, `amin`, and `round_`, respectively.
```
>>> {n: type(v).__name__ for n in sorted(set(dir(np)).difference(np.__all__)) if not n.startswith('_') and not inspect.ismodule(v := getattr(np, n))}
{'Tester': 'type', 'abs': 'ufunc', 'kernel_version': 'tuple', 'max': 'function', 'min': 'function', 'numarray': 'str', 'oldnumeric': 'str', 'round': 'function', 'test': 'PytestTester', 'use_hugepage': 'int'}
>>> np.abs is np.absolute
True
```

2021-11-12 10:17 UTC, kmaehashi commented
Makes sense, fixed 😃

2021-11-12 10:19 UTC, toslunar approved these changes

2021-11-13 12:00 UTC, merged