Add trapz
cupy/cupy pull request #6107
Opened 2021-11-17 04:00 UTC by ColmTalbot

Hi!

This PR adds a version of trapz as requested in https://github.com/cupy/cupy/issues/6078. This is my first contribution here, I hope it's the expected format/sufficiently tested and documented.

I've been using a version of this in [code for gravitational-wave astronomy](https://github.com/ColmTalbot/gwpopulation/blob/master/gwpopulation/cupy_utils.py#L49) for a while.

2021-11-17 07:05 UTC, takagi requested changes
Thanks for your contribution! Would you check a few comments? I'll kick the CI after the changes. BTW, gravitational-wave astronomy sounds super cool.

2021-11-17 07:05 UTC, takagi commented on tests/cupy_tests/math_tests/test_sumprod.py
> +@testing.gpu
For a historical reason, we no longer need `@testing.gpu` decorator. Would you remove it?

2021-11-18 02:05 UTC, takagi approved these changes

2021-11-18 02:06 UTC, takagi commented
Thanks! It's going to be merged soon after the CI passes.

2021-11-18 05:56 UTC, takagi commented on tests/cupy_tests/math_tests/test_sumprod.py
> +    @testing.numpy_cupy_allclose()
Would you relax the tolerance for FP16?
```suggestion
    @testing.numpy_cupy_allclose(rtol={numpy.float16: 1e-3, 'default': 1e-7})
```

2021-11-18 06:15 UTC, takagi commented
/test

2021-11-18 07:56 UTC, takagi commented
/test

2021-11-18 07:56 UTC, takagi approved these changes

2021-11-18 12:28 UTC, kmaehashi commented
pfnCI, run Jenkins please.

2021-11-18 13:06 UTC, merged