Unwrap functions wrapped by contextmanager for linkcode
cupy/cupy pull request #6126
Opened 2021-11-18 17:08 UTC by kmaehashi

This fixes `[source]` deadlinks for wrapped functions, e.g.:

* https://docs.cupy.dev/en/v10.0.0rc1/reference/generated/cupy.cuda.using_allocator.html?highlight=[source]
* https://docs.cupy.dev/en/v10.0.0rc1/reference/generated/cupyx.optimizing.optimize.html?highlight=[source]

2021-12-04 09:52 UTC, toslunar requested changes

2021-12-04 09:52 UTC, toslunar commented on docs/source/conf.py
> +        raise RuntimeError(f'nested too deep: {info}')
```suggestion
    obj = inspect.unwrap(obj)
```

2021-12-04 09:52 UTC, toslunar commented on docs/source/conf.py
> +        tag, relpath if linenum is None else f'{relpath}#L{linenum}')
Could you avoid repeating `relpath`?  For example,
```python
fragment = ''
...
    fragment = f'#L{linenum}'
...
return f'https://github.com/cupy/cupy/blob/{tag}/{relpath}{fragment}'

2021-12-05 05:34 UTC, kmaehashi commented on docs/source/conf.py
> +        raise RuntimeError(f'nested too deep: {info}')
wow didn't know this, thanks :)

2021-12-06 01:09 UTC, toslunar approved these changes
LGTM

2021-12-06 01:10 UTC, merged