Add doc issue template
cupy/cupy pull request #6294
Opened 2022-01-06 04:25 UTC by khushi-411

Hi, Team!
The PR Fixes: https://github.com/cupy/cupy/issues/6293#issue-1094716054

cc: @kmaehashi @leofang @toslunar

2022-01-07 04:55 UTC, kmaehashi commented
Thanks, basically LGTM!
Could you fix errors? https://github.com/cupy/cupy/blob/06ad27b7a3cd2d6a5a7fa8dd43062bc1e9319df4/.github/ISSUE_TEMPLATE/documentation.yml

2022-01-07 07:50 UTC, khushi-411 commented
Hi, @kmaehashi!
I made the required fixes. Could you please view it?

Here's the link to the file: https://github.com/cupy/cupy/blob/8d45e64baa2a7880bf7e690423eec023beaee277/.github/ISSUE_TEMPLATE/documentation.yml

Thanks (:

2022-01-12 06:58 UTC, kmaehashi requested changes
Thanks!

2022-01-12 06:58 UTC, kmaehashi commented on .github/ISSUE_TEMPLATE/documentation.yml
> +      label: The doc issue
```suggestion
      label: Description
```

2022-01-12 06:58 UTC, kmaehashi commented on .github/ISSUE_TEMPLATE/documentation.yml
> +        Please give a clear description of the doc issue. Make sure to provide relevant links to the document you are referring to.
```suggestion
        Please describe the issue with the current documentation. Make sure to provide relevant links to the document you are referring to.
```

2022-01-12 07:11 UTC, merged

2022-01-12 07:19 UTC, khushi-411 commented
Thanks a lot for reviewing, @kmaehashi! :)