CI: Add `cuda-slow` test in FlexCI
cupy/cupy pull request #6335
Opened 2022-01-17 14:03 UTC by kmaehashi

2022-01-17 14:04 UTC, kmaehashi commented
Testing: https://ci.preferred.jp/cupy.linux.cuda-slow/91281/

2022-01-18 00:42 UTC, toslunar requested changes

2022-01-18 00:42 UTC, toslunar commented on .pfnci/config.tags.json
> +    "cupy.linux.cuda-head": ["slow"],
```suggestion
    "cupy.linux.cuda-slow": ["slow"],
```

2022-01-18 01:06 UTC, kmaehashi commented on .pfnci/config.tags.json
> +    "cupy.linux.cuda-head": ["slow"],
:+1::bow:

2022-01-18 04:20 UTC, toslunar approved these changes

2022-01-18 04:20 UTC, toslunar commented
/test slow

2022-01-18 04:22 UTC, merged