Fix `cupy.fill` to properly take `cupy.ndarray`
cupy/cupy pull request #6481
Opened 2022-02-18 08:15 UTC by takagi

Close #6437.

2022-03-14 06:41 UTC, toslunar requested changes
The implementation LGTM and I roughly checked that both NumPy and CuPy `fill` the value like `copyto`, i.e. the `'unsafe'` casting with ComplexWarning.

I left comments on the test.  Besides, it seems better to compare the 3 cases

- `numpy.ndarray.fill(numpy.ndarray)`
- `cupy.ndarray.fill(numpy.ndarray)`
- `cupy.ndarray.fill(cupy.ndarray)`

but such refactoring is optional.  (I don't come up with an elegant way.)

2022-03-14 06:41 UTC, toslunar commented on tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
> +    def test_fill_with_cupy_scalar_ndarray(self, dtype):
How about using `@testing.numpy_cupy_array_equal`?

2022-03-14 06:41 UTC, toslunar commented on tests/cupy_tests/core_tests/test_ndarray_copy_and_view.py
>      @testing.for_all_dtypes()
How about testing casts by `for_all_dtypes_combination`?

2022-03-14 06:41 UTC, toslunar commented on cupy/_core/core.pyx
> +                    'non-scalar cupy.ndarray cannot be used for fill')
The message LGTM because it's consistent with the `numpy.ndarray` case below.

2022-03-15 08:04 UTC, takagi commented
PTAL! For comparing the 3 cases above, I think comparing the following two makes sense:
- `numpy.ndarray.fill(numpy.ndarray)` and `cupy.ndarray.fill(numpy.ndarray)`
- `numpy.ndarray.fill(numpy.ndarray)` and `cupy.ndarray.fill(cupy.ndarray)`

They are corresponding to `test_fill_with_numpy_scalar_ndarray` and `test_fill_with_cupy_scalar_ndarray`.

2022-03-15 08:23 UTC, toslunar approved these changes
LGTM

2022-03-15 08:24 UTC, toslunar commented
/test mini

2022-03-15 10:11 UTC, merged