Support NCCL 2.12.7
cupy/cupy pull request #6534
Opened 2022-03-08 07:36 UTC by takagi

2022-03-10 06:59 UTC, kmaehashi requested changes

2022-03-10 06:59 UTC, kmaehashi commented on .pfnci/schema.yaml
> +      "11.5":
```suggestion
```

The release notes says: This NCCL release supports [CUDA 10.2](https://docs.nvidia.com/cuda/archive/10.2/index.html), [CUDA 11.0](https://docs.nvidia.com/cuda/archive/11.0/index.html), and [CUDA 11.6](https://docs.nvidia.com/cuda/archive/11.6/index.html).

https://docs.nvidia.com/deeplearning/nccl/release-notes/rel_2-12-7.html#rel_2-12-7

2022-03-10 07:29 UTC, kmaehashi commented
The library installer also needs to be fixed for CUDA versions not supported by NCCL 2.12. 😅

2022-03-10 07:56 UTC, takagi commented
Fixed!

2022-03-10 08:11 UTC, kmaehashi commented
It seems a garbage file is in the commit 😅

2022-03-10 08:18 UTC, takagi commented
oops...

2022-03-10 08:22 UTC, kmaehashi commented
Sorry to comment sporadically :bow: could you enable NCCL 2.12 in CUDA 11.0? Otherwise we have no way to test NCCL 2.12 in CI.

2022-03-10 09:20 UTC, takagi commented
ah, we can't test it in cuda116 yet...

2022-03-16 06:54 UTC, kmaehashi commented
/test full

2022-03-16 06:54 UTC, kmaehashi approved these changes

2022-03-16 08:07 UTC, kmaehashi commented
/test jenkins

2022-03-16 11:27 UTC, kmaehashi commented
cupyx.distributed test failing with timeout :thinking:
https://ci.preferred.jp/cupy.linux.cuda110.multi/97051/197863#L7888

/test multi

2022-03-29 11:29 UTC, kmaehashi commented
Changing target to the next month release.

2022-04-15 06:24 UTC, takagi commented
/test full

2022-04-19 06:29 UTC, takagi commented
I failed to reproduce the timeout on my local.

2022-06-14 04:18 UTC, kmaehashi commented
TODO: use NCCL 2.12 in CUDA 11.7 test (https://github.com/cupy/cupy/pull/6767#discussion_r896358629)

2022-06-14 04:20 UTC, takagi commented
I hope it works...

2022-08-30 04:11 UTC, kmaehashi commented
/test full

2022-08-30 04:25 UTC, kmaehashi commented
/test full

2022-09-28 06:20 UTC, takagi commented
No v2.14 yet. https://developer.download.nvidia.com/compute/redist/nccl/

2022-09-28 07:32 UTC, kmaehashi commented
https://developer.download.nvidia.com/compute/redist/nccl/v2.14/nccl_2.14.3-1+cuda11.7_x86_64.txz

2022-09-29 00:45 UTC, kmaehashi commented on cupyx/tools/install_library.py
> +    'nccl_2.14.3-1+cuda11.4_x86_64.txz'))
```suggestion
    'nccl_2.14.3-1+cuda11.7_x86_64.txz'))
```

2022-09-29 00:46 UTC, kmaehashi commented
/test mini

2022-09-29 00:46 UTC, kmaehashi approved these changes

2022-09-29 04:30 UTC, merged