Skip cooperative groups in CUDA-Python when toolkit < 1.6
cupy/cupy pull request #6652
Opened 2022-04-13 07:54 UTC by emcastillo

Should fix CIs

2022-04-13 07:54 UTC, emcastillo commented
/test cuda-python

2022-04-13 08:24 UTC, emcastillo commented
/test cuda-python

2022-04-13 13:57 UTC, leofang requested changes

2022-04-13 13:57 UTC, leofang commented on tests/cupyx_tests/jit_tests/test_cooperative_groups.py
> +            and cupy.cuda.nvrtc.get_version() < (11, 6)),
```suggestion
            and cupy.cuda.nvrtc.getVersion() < (11, 6)),
```

2022-04-13 13:57 UTC, leofang commented on tests/cupyx_tests/jit_tests/test_cooperative_groups.py
> +            and cupy.cuda.nvrtc.get_version() < (11, 6)),
```suggestion
            and cupy.cuda.nvrtc.getVersion() < (11, 6)),
```

2022-04-14 00:02 UTC, emcastillo commented
/test cuda-python

2022-04-14 02:44 UTC, emcastillo commented
/test jenkins

2022-04-14 03:53 UTC, leofang approved these changes
LGTM, thanks Emilio! The changes to `runtime.pxd` should be backported 😅

2022-04-14 04:35 UTC, kmaehashi commented
* https://github.com/cupy/cupy/pull/6604
* Manually backported to v10 (#6654)

2022-04-14 04:35 UTC, kmaehashi approved these changes

2022-04-14 04:35 UTC, merged