Fix to return correct CUDA version when in CUDA Python mode
cupy/cupy pull request #6736
Opened 2022-05-23 08:47 UTC by kmaehashi

This will allow using `cudaRuntimeGetVersion()` in all locations where branch based on the current CUDA version (to test feature availability) is needed.

2022-05-23 14:31 UTC, leofang approved these changes

2022-05-24 01:48 UTC, emcastillo commented
/test mini

2022-05-24 01:48 UTC, emcastillo approved these changes

2022-05-24 05:58 UTC, kmaehashi commented
This is primarily needed for #6730 so not backporting to avoid breaking existing behavior.

2022-05-24 06:08 UTC, emcastillo requested changes

2022-05-24 06:08 UTC, emcastillo commented on tests/cupy_tests/cuda_tests/test_runtime.py
> +def test_assumed_runtime_version():
This test fails on hip

2022-05-24 06:09 UTC, emcastillo commented on tests/cupy_tests/cuda_tests/test_runtime.py
> +def test_assumed_runtime_version():
```
12:50:19     def test_assumed_runtime_version():
12:50:19         # When CUDA Python is enabled, CuPy calculates the CUDA runtime version
12:50:19         # from NVRTC version. This test ensures that the assumption is correct
12:50:19         # by running the same logic in non-CUDA Python environment.
12:50:19         # When this fails, `runtime.runtimeGetVersion()` logic needs to be fixed.
12:50:19         (major, minor) = nvrtc.getVersion()
12:50:19 >       assert runtime.runtimeGetVersion() == major * 1000 + minor * 10
12:50:19 E       assert 3275 == ((9 * 1000) + (0 * 10))
12:50:19 E        +  where 3275 = <built-in function runtimeGetVersion>()
12:50:19 E        +    where <built-in function runtimeGetVersion> = runtime.runtimeGetVersion
12:50:19 
12:50:19 major      = 9
12:50:19 minor      = 0
```

2022-05-24 06:20 UTC, kmaehashi commented on tests/cupy_tests/cuda_tests/test_runtime.py
> +def test_assumed_runtime_version():
Ah, right, will fix shortly.

2022-05-24 06:30 UTC, emcastillo commented
/test mini

2022-06-10 04:14 UTC, emcastillo commented
/test mini

2022-06-14 05:30 UTC, kmaehashi commented
Tests passed, could you approve? @emcastillo :)

2022-06-15 04:59 UTC, emcastillo approved these changes

2022-06-15 04:59 UTC, merged