Support CUDA 11.7
cupy/cupy pull request #6767
Opened 2022-06-03 04:36 UTC by takagi

2022-06-07 03:39 UTC, takagi commented
Review ready!

2022-06-14 02:57 UTC, kmaehashi commented
/test mini

2022-06-14 02:57 UTC, kmaehashi approved these changes
LGTM!

2022-06-14 02:58 UTC, kmaehashi commented
Running CUDA 11.7 test: https://ci.preferred.jp/cupy.linux.cuda117/103427/

2022-06-14 04:18 UTC, kmaehashi requested changes

2022-06-14 04:18 UTC, kmaehashi commented on .pfnci/schema.yaml
> +        alias: "11.7"
https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/
```
libcudnn8_8.4.0.27-1+cuda10.2_amd64.deb 224MB 2022-04-01 02:25
libcudnn8_8.4.0.27-1+cuda11.6_amd64.deb 402MB 2022-04-01 02:21
libcudnn8_8.4.1.50-1+cuda10.2_amd64.deb 225MB 2022-05-22 20:26
libcudnn8_8.4.1.50-1+cuda11.6_amd64.deb 401MB 2022-05-20 22:34
```

```suggestion
        alias: "11.6"
```

2022-06-14 04:18 UTC, kmaehashi commented on .pfnci/matrix.yaml
> +  nccl: "2.11"
```suggestion
  nccl: null  # TODO use 2.12 once supported
```

2022-06-14 04:24 UTC, takagi commented
/test mini

2022-06-14 05:26 UTC, kmaehashi commented
regenerated.

2022-06-14 05:27 UTC, kmaehashi commented
/test mini

Testing cuda 11.7 https://ci.preferred.jp/cupy.linux.cuda117/103464/

2022-06-14 07:18 UTC, kmaehashi commented
cuda116 test failure is known flaky #5813

2022-06-20 00:52 UTC, merged