Support `keepdims` parameter for `average`
cupy/cupy pull request #6852
Opened 2022-07-04 01:24 UTC by takagi

Part of https://github.com/cupy/cupy/issues/6821, following a change of NumPy 1.23.

https://numpy.org/devdocs/release/1.23.0-notes.html#keepdims-parameter-for-average

2022-07-05 09:58 UTC, toslunar requested changes
Could you add `returned=True` tests?  (By the way, we no longer need `check_returned` because `numpy_cupy_allclose` supports tuple.)

```
>>> np.average(np.arange(6).reshape(2, 3), weights=np.arange(1, 7).reshape(2, 3), axis=0, returned=True)
(array([2.4       , 3.14285714, 4.        ]), array([5., 7., 9.]))
>>> np.average(np.arange(6).reshape(2, 3), weights=np.arange(1, 7).reshape(2, 3), axis=0, returned=True, keepdims=True)
(array([[2.4       , 3.14285714, 4.        ]]), array([[5., 7., 9.]]))
```

2022-07-11 03:42 UTC, takagi commented
Thanks, PTAL!

2022-07-12 04:23 UTC, toslunar commented
/test mini

2022-07-13 02:29 UTC, toslunar requested changes
With the current branch, I got this diff:
```
>>> for xp in (numpy, cupy): xp.average(xp.arange(6).reshape(2, 3), weights=xp.arange(1, 7).reshape(2, 3), axis=1, keepdims=True)
... 
array([[1.33333333],
       [4.13333333]])
array([[ 1.33333333,  0.53333333],
       [10.33333333,  4.13333333]])
```

2022-07-13 14:00 UTC, takagi commented
ah, numpy 1.23.1 fixed a bug in https://github.com/numpy/numpy/pull/21868, and we should follow this.

2022-07-25 06:15 UTC, takagi commented
/test mini

2022-07-25 09:40 UTC, toslunar approved these changes
LGTM

2022-07-25 09:41 UTC, merged