Support `deg` in `cupy.angle`
cupy/cupy pull request #6905
Opened 2022-07-26 06:20 UTC by emcastillo

There are numerical issues so for negative numbers I try to avoid using fp16 type and anything promoting to fp16.
numyp does the full calc in fp16 resulting in 179.9 due to numerical issues. CuPy just returns 180

2022-07-26 08:06 UTC, kmaehashi requested changes
LGTM except for nits!

2022-07-26 08:06 UTC, kmaehashi commented on cupy/_core/_routines_math.pyx
> +    'cupy_angle',
Let's avoid giving the same kernel name as it can be confusing when profiling.
```suggestion
    'cupy_angle_deg',
```

2022-07-26 08:06 UTC, kmaehashi commented on tests/cupy_tests/math_tests/test_arithmetic.py
> +        if self.name in ('angle'):
```suggestion
        if self.name in {'angle'}:
```

2022-07-26 08:28 UTC, emcastillo commented
fixed!

2022-07-26 08:34 UTC, kmaehashi commented
/test mini

2022-07-26 08:34 UTC, kmaehashi approved these changes

2022-07-26 13:17 UTC, merged

2022-07-27 00:54 UTC, jakirkham commented
Thanks all! 🙏

2022-07-27 00:56 UTC, jakirkham commented
Will this be included in CuPy 11.0.0?

2022-07-27 00:57 UTC, kmaehashi commented
> Will this be included in CuPy 11.0.0?

Yes.