Implement delete function, add documentation
cupy/cupy pull request #7359
Opened 2023-02-01 02:01 UTC by Anas20001

2023-02-01 05:23 UTC, kmaehashi requested changes
Thanks for the PR, @Anas20001!
Although I think there is room for optimizations based on how `indices` is given, the current implementation is great as an initial implementation for `cupy.delete`.

* Could you remove `cupy.asarray(arr)` call? In general, CuPy does not allow inputs other than cupy.ndarray.
* Could you add a fast path in case `indices` is given as a mask on GPU (cupy.ndarray of bool dtype)?
* Let's add a warning (as in `cupy.compress`) to docs as this function may synchronize the device. Also add `See also` section that links to NumPy API docs.  c.f. https://docs.cupy.dev/en/stable/reference/generated/cupy.compress.html
* Please add a test code.

2023-02-08 03:11 UTC, Anas20001 commented
Hi @kmaehashi 
 I wanted to let you know that I have taken your feedback into consideration and made the necessary changes to the cupy.delete implementation.
Please let me know if you would like me to make any further changes or if you are ready to review the changes I have made. I look forward to hearing back from you soon.

2023-02-09 08:57 UTC, kmaehashi requested changes

2023-02-09 08:57 UTC, kmaehashi commented on cupy/__init__.py
> -from cupy._manipulation.add_remove import delete
Could you add this back here, with `# NOQA` comment? This is needed to make the API public as `cupy.delete`.

2023-02-09 08:57 UTC, kmaehashi commented on cupy/__init__.py
> -from cupy._manipulation.add_remove import delete
Also add `delete` under `Adding and removing elements` section of the docs (`docs/source/reference/manipulation.rst`):
https://docs.cupy.dev/en/stable/reference/manipulation.html#adding-and-removing-elements

c.f. https://numpy.org/doc/stable/reference/routines.array-manipulation.html

2023-02-09 08:57 UTC, kmaehashi commented on cupy/_manipulation/add_remove.py
> +    See also:
Use reST directive `.. seealso::` (see docs of other methods for the usage)

2023-02-09 08:57 UTC, kmaehashi commented on cupy/_manipulation/add_remove.py
> +    Warning:
`.. warning::`

2023-02-09 08:57 UTC, kmaehashi commented on cupy/_manipulation/add_remove.py
> +        indices (array_like):
```suggestion
        indices (slice, int or array of ints):
```

2023-02-09 08:57 UTC, kmaehashi commented on cupy/_manipulation/add_remove.py
> +            copy of `arr`.
```suggestion
            copy of `arr`.
            Boolean indices are treated as a mask of elements to remove.
```

2023-02-09 08:57 UTC, kmaehashi commented on tests/cupy_tests/manipulation_tests/test_add_remove.py
> +        return xp.delete(arr, indices)
Could you add test cases where indices are `slice` or `int`? This will prevent future errors when optimizing `cupy.delete`.

2023-02-09 21:54 UTC, Anas20001 commented
Dear @kmaehashi 
I have taken your feedback into consideration and made the necessary changes . 
I look forward to hearing back from you soon.

2023-02-13 06:07 UTC, kmaehashi commented
/test mini

2023-02-13 06:08 UTC, kmaehashi approved these changes
Thanks, LGTM! :+1:

2023-02-13 06:09 UTC, kmaehashi commented on cupy/_manipulation/add_remove.py
> +    .. warning: This function may synchronize the device.
```suggestion
    .. warning:: This function may synchronize the device.
```

2023-02-13 06:10 UTC, kmaehashi commented
/test mini

2023-02-13 06:10 UTC, kmaehashi approved these changes

2023-02-20 15:44 UTC, kmaehashi commented
It seems the test code hits a ROCm issue regarding indexing.

```
15:46:15 cupy_tests/manipulation_tests/test_add_remove.py ...Fatal Python error: Aborted
15:46:15 
15:46:15 Thread 0x00007f6b13af6740 (most recent call first):
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/cupy/_manipulation/add_remove.py", line 40 in delete
15:46:15   File "/tmp/tmp.ooKJVWRWXl/tests/cupy_tests/manipulation_tests/test_add_remove.py", line 52 in test_delete_with_indices_as_int
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/cupy/testing/_loops.py", line 45 in _call_func
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/cupy/testing/_loops.py", line 70 in _call_func_cupy
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/cupy/testing/_loops.py", line 94 in _call_func_numpy_cupy
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/cupy/testing/_loops.py", line 273 in test_func
15:46:15   File "/opt/pyenv/versions/3.10.0/lib/python3.10/unittest/case.py", line 549 in _callTestMethod
15:46:15   File "/opt/pyenv/versions/3.10.0/lib/python3.10/unittest/case.py", line 591 in run
15:46:15   File "/opt/pyenv/versions/3.10.0/lib/python3.10/unittest/case.py", line 650 in __call__
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/_pytest/unittest.py", line 330 in runtest
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/_pytest/runner.py", line 167 in pytest_runtest_call
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/_pytest/runner.py", line 260 in <lambda>
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/_pytest/runner.py", line 339 in from_call
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/_pytest/runner.py", line 259 in call_runtest_hook
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/_pytest/runner.py", line 220 in call_and_report
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/_pytest/runner.py", line 131 in runtestprotocol
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/_pytest/runner.py", line 112 in pytest_runtest_protocol
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/_pytest/main.py", line 349 in pytest_runtestloop
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/_pytest/main.py", line 324 in _main
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/_pytest/main.py", line 270 in wrap_session
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/_pytest/main.py", line 317 in pytest_cmdline_main
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 167 in main
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 190 in console_main
15:46:15   File "/tmp/.local/lib/python3.10/site-packages/pytest/__main__.py", line 5 in <module>
15:46:15   File "/opt/pyenv/versions/3.10.0/lib/python3.10/runpy.py", line 86 in _run_code
15:46:15   File "/opt/pyenv/versions/3.10.0/lib/python3.10/runpy.py", line 196 in _run_module_as_main
```

Could you add XFAIL to `test_delete_with_indices_as_int` test, similar to #4653?

```py
     if cupy.cuda.runtime.is_hip:
         pytest.xfail('HIP may have a bug')
```

2023-02-28 05:11 UTC, Anas20001 commented
Dear @kmaehashi , I have added the fix in a previous commit, but a Docs Build issue came up. I was looking over it in the couple of days but didn't solve it, do you have any hint to start from ?

2023-02-28 05:27 UTC, leofang commented
If you rerun the CI the problem should go away. Our doc website had an issue that's resolved now.

2023-02-28 05:42 UTC, Anas20001 commented
> If you rerun the CI the problem should go away. Our doc website had an issue that's resolved now.

Thanks @leofang for your informative response.

2023-02-28 05:44 UTC, kmaehashi commented
I've retriggered CI, it should pass :)

2023-02-28 07:51 UTC, kmaehashi commented
@Anas20001 We are about to cut a release, so let me trigger the remaining tests for this PR later this week.

2023-03-05 07:03 UTC, kmaehashi commented
/test mini

2023-03-05 07:03 UTC, kmaehashi approved these changes

2023-03-11 05:55 UTC, kmaehashi commented
Jenkins failure seems unrelated, let's merge!

2023-03-11 05:55 UTC, merged