Add Lazy Loading for cupyx.scipy.* submodules
cupy/cupy pull request #7416
Opened 2023-02-20 18:49 UTC by Raghav323

PR to add support for lazy loading of cupyx.scipy.* submodules using `__getattr__` as Scipy does .
**Linked Issue**: #7392

2023-03-01 14:13 UTC, Raghav323 commented
Could you please review @kmaehashi

2023-03-01 14:28 UTC, kmaehashi requested changes

2023-03-01 14:28 UTC, kmaehashi commented on cupyx/scipy/__init__.py
> +    return __all__
This needs to export `get_array_module`.

2023-03-01 14:28 UTC, kmaehashi commented on cupyx/scipy/__init__.py
> +        return _importlib.import_module(f'scipy.{name}')
This is returning SciPy module instead of CuPy, and not raising an error for undefined attributes.

2023-03-18 04:58 UTC, Raghav323 commented
Could you please review @kmaehashi

2023-03-22 07:16 UTC, kmaehashi commented
Thanks, but just adding `__getattr__` seems insufficient to support lazy loading, as these `cupyx.scipy` modules are imported automatically via `import cupy`. 

```
$ python -c 'import sys, cupy; print([x for x in sys.modules.keys() if "cupyx.scipy" in x])'
['cupyx.scipy.sparse._util', 'cupyx.scipy.sparse._sputils', 'cupyx.scipy.sparse._base', 'cupyx.scipy.sparse._data', 'cupyx.scipy.sparse._index', 'cupyx.scipy.sparse._compressed', 'cupyx.scipy.sparse._csc', 'cupyx.scipy.sparse._csr', 'cupyx.scipy.sparse._coo', 'cupyxscipy.sparse._dia', 'cupyx.scipy.sparse._construct', 'cupyx.scipy.sparse._extract', 'cupyx.scipy.sparse', 'cupyx.scipy', 'cupyx.scipy.fft._fft', 'cupyx.scipy.special._complexstuff', 'cupyx.scipy.special._trig', 'cupyx.scipy.special._loggamma', 'cupyx.scipy.special._gamma', 'cupyx.scipy.special._bessel', 'cupyx.scipy.special._digamma', 'cupyx.scipy.special._zeta', 'cupyx.scipy.special._gammainc', 'cupyx.scipy.special._beta', 'cupyx.scipy.special._stats_distributions', 'cupyx.scipy.special._statistics', 'cupyx.scipy.special._convex_analysis', 'cupyx.scipy.special._gammaln', 'cupyx.scipy.special._gammasgn', 'cupyx.scipy.special._polygamma', 'cupyx.scipy.special._poch', 'cupyx.scipy.special._erf', 'cupyx.scipy.special._lpmv', 'cupyx.scipy.special._sph_harm', 'cupyx.scipy.special._exp1', 'cupyxscipy.special._expi', 'cupyx.scipy.special._expn', 'cupyx.scipy.special._softmax', 'cupyx.scipy.special._logsoftmax', 'cupyx.scipy.special._basic', 'cupyx.scipy.special._xlogy', 'cupyx.scipy.special._logsumexp', 'cupyx.scipy.special', 'cupyx.scipy.fft._fftlog', 'cupyx.scipy.fft._helper', 'cupyx.scipy.fftpack._fft', 'cupyx.scipy.fftpack', 'cupyx.scipy.fft._realtransforms', 'cupyx.scipy.fft']
```

2023-05-10 05:31 UTC, kmaehashi commented
I think this requires some extra work than initially expected in #7392. Let me know if you still want to work on this one.

2023-06-05 16:26 UTC, kmaehashi commented
Let me close this one for now as it's been a draft for a while, but feel free to reopen when you have time to resume working on. Thanks!

2023-06-05 16:26 UTC, closed without merging