Added `scipy.special.binom` functionality to CuPy
cupy/cupy pull request #7463
Opened 2023-03-13 10:24 UTC by KyanCheung

2023-03-14 04:42 UTC, emcastillo commented on cupyx/scipy/special/_combinatorics.py
> +    doc="""The number of combinations of N things taken k at a time.
Shouldn't this function being imported in `__init__` and have its tests too? 😃

2023-03-14 04:43 UTC, emcastillo requested changes
Looks neat!
Please either add tests for `comb` or lets remove it from this PR is you plan to work on it later :)

2023-03-14 10:27 UTC, KyanCheung commented
Ah sorry, didn't mean to upload `comb` as well. I programmed it, but decided that I'd only upload `binom` first afterwards. 

After this PR finishes, I'll make a separate PR for `comb` and `perm` implementation.

2023-03-15 02:19 UTC, emcastillo commented
/test mini

2023-03-15 02:19 UTC, emcastillo approved these changes
Awesome work! thanks!

2023-03-17 06:57 UTC, emcastillo commented
/test mini

2023-03-22 05:29 UTC, emcastillo commented
seems like CI failures are real

2023-03-25 10:10 UTC, KyanCheung commented
Sorry all, I've been busy with other things and I couldn't fix the tests.

I've checked `test_binom` on my GPU and things are luckily working now on my end.

2023-03-28 01:50 UTC, emcastillo commented
/test mini

2023-03-28 08:55 UTC, KyanCheung commented
Seems like the errors were caused by the error tolerance being too tight. That being said, there were 22 failures and I only had 6 tests. Something else going on?

2023-03-28 11:13 UTC, KyanCheung commented
The failed tests all seem to be unrelated to the code I added?

2023-03-29 08:54 UTC, KyanCheung commented
Also one thing I've noticed now - do I add `#NOQA` to the function import as well in `_init_`? What does it do?

2023-03-31 02:39 UTC, emcastillo commented on cupyx/scipy/special/__init__.py
> +from cupyx.scipy.special._binom import binom
```suggestion
from cupyx.scipy.special._binom import binom  # NOQA
```

2023-03-31 02:40 UTC, emcastillo commented
> Also one thing I've noticed now - do I add #NOQA to the function import as well in _init_? What does it do?

It is used to avoid linter errors

2023-03-31 02:40 UTC, emcastillo commented
/test mini

2023-03-31 03:18 UTC, emcastillo commented on cupyx/scipy/special/_binom.py
> +)
```suggestion
)

```

2023-03-31 03:19 UTC, emcastillo commented on tests/cupyx_tests/scipy_tests/special_tests/test_binom.py
> +        return scp.special.binom(a[:, xp.newaxis], a[xp.newaxis, :])
```suggestion
        return scp.special.binom(a[:, xp.newaxis], a[xp.newaxis, :])

```

2023-04-02 02:34 UTC, KyanCheung commented
/test mini

2023-04-02 04:55 UTC, emcastillo commented
/test mini

2023-04-03 01:19 UTC, emcastillo approved these changes

2023-04-03 01:20 UTC, merged