Let the user specify a starting vector for eigsh.
cupy/cupy pull request #7487
Opened 2023-03-28 05:32 UTC by jmbr

Sometimes a good initial guess for an eigenvector is known and it is advantageous to use it within the eigensolver. This patch adds the keyword argument ``v0`` to ``eigsh`` so that it behaves in the same way as in ``scipy.sparse.linalg``.

2023-03-29 04:48 UTC, kmaehashi requested changes
Thanks, LGTM except minor comment. Could you add test code for `v0 != None` case?

2023-03-29 04:48 UTC, kmaehashi commented on cupyx/scipy/sparse/linalg/_eigen.py
> +        V[0] = cupy.asarray(v0)
In CuPy, ndarray arguments must always be `cupy.ndarray` to avoid implicit host-to-device copy. So could you remove `cupy.asarray` here?

2023-03-29 18:25 UTC, jmbr commented
> Thanks, LGTM except minor comment. Could you add test code for `v0 != None` case?

I have added the requested test in the last commit.

2023-05-10 05:29 UTC, kmaehashi commented
/test mini

2023-05-10 05:29 UTC, kmaehashi approved these changes
Hi, sorry for the delay in review. LGTM!

2023-06-03 14:38 UTC, jmbr commented
Hi, is there a pending step on my end to get this pull request merged? Please let me know if that's the case so I can help.

2023-06-05 06:40 UTC, kmaehashi commented
Hi @jmbr, sorry for the delay! Test failures are irrelevant, so let's proceed to merge.

2023-06-05 06:40 UTC, merged

2024-06-16 19:04 UTC, YanivDorGalron commented
Hey, 
Thanks for the helpful discussion
In the eigsh function i can determine the number of eigenvectors to calculate. 
how can i use v0 if i have a different initial guess for each of the k eigenvectors?