12.5 Tests
cupy/cupy pull request #8337
Opened 2024-05-24 09:59 UTC by johnnynunez

cuda 12.5 is out

2024-06-19 09:06 UTC, kmaehashi requested changes
Thanks!

2024-06-19 09:06 UTC, kmaehashi commented on .pfnci/matrix.yaml
> +  cusparselt: "0.2.0"
```suggestion
  cusparselt: "0.6.1"
```

2024-06-19 09:06 UTC, kmaehashi commented on .pfnci/schema.yaml
> +      "12.5":
CUDA 12.5 requires NCCL 2.21.

2024-06-19 09:06 UTC, kmaehashi commented on .pfnci/schema.yaml
> +      "11.8":
https://docs.nvidia.com/cuda/cusparselt/release_notes.html#cusparselt-v0-5-0
> cuSPARSELt requires CUDA 12.0 or above

2024-06-20 09:00 UTC, johnnynunez commented
> Also please remove this line: https://github.com/cupy/cupy/pull/8337/files#diff-c5351c21fb860332e41aa81e1599475f79f63e2bc47e0f32922c721c2cbbc749R337

what lines?
![image](https://github.com/cupy/cupy/assets/22727137/8003c17b-2cb8-4df1-b371-84640d6f09cf)

2024-07-10 05:15 UTC, kmaehashi commented on .pfnci/schema.yaml
> +      "1.24":
```suggestion
      "12.4":
```

2024-07-10 05:17 UTC, kmaehashi commented on .pfnci/matrix.yaml
> +  nccl: "2.20"
```suggestion
  nccl: "2.21"
```

2024-07-10 05:26 UTC, kmaehashi commented
Hi, sorry for keeping you waiting! I've kicked new tests so let's see how it goes :eyes:

https://ci.preferred.jp/cupy.linux.cuda125/164614/
https://ci.preferred.jp/cupy.linux.cuda125.multi/164615/
https://ci.preferred.jp/cupy.win.cuda125/164613/

2024-07-11 00:43 UTC, kmaehashi commented
All tests green (and without timeout), merging. Thanks again @johnnynunez!

2024-07-11 00:43 UTC, merged

2024-07-11 02:08 UTC, kmaehashi commented
Will backport after #8422